# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  todoappapi:
    image: todoappapi
    build:
      context: .
      dockerfile: api/TodoApp/TodoApp.Api/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 32770:32770
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
