version: '3.8'

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
    image: todo-app:production
    container_name: todo-app-production
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
